### ISSUE TITLE
Getting an OBO token in a callback

### ISSUE THREAD

**Issue by hrazmsft** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#24] opened 2020-08-12 20:18 UTC
How can I get an OBO access token in a callback like:

```
[HttpPost]
public IActionResult ProcessData(string data)
{
    var processor = new Processor();

    processor.Finished += async (s, e) =>
    {
        var accessToken = await this
            ._tokenAcquisition
            .GetAccessTokenForUserAsync(new[] { "Files.ReadWrite" }, user: this.User);

        await WriteToOneDrive(accessToken, e.Data);
    };

    processor.processAsync(data); // Run async without awaiting

    return NoContent();
}
```

In this case the `this.User` is already disposed, and even without it, `GetAccessTokenForUserAsync` crashes with NullObjectException.

My process takes a very long time (hours).

How can I get the token inside a callback when I need it?

**Comment by TiagoBrenck** [comment] 2020-08-12 21:23
Hello @hraz-msft, according to `Microsoft.Identity.Web` documentation for the method `GetAccessTokenForUserAsync()`, I dont think you need to pass the user, since it is used for extra claims purpose. Here is what they wrote:
```//
        // Summary:
        //     Typically used from an ASP.NET Core Web App or Web API controller, this method
        //     gets an access token for a downstream API on behalf of the user account which
        //     claims are provided in the Microsoft.AspNetCore.Http.HttpContext.User member
        //     of the controller's Microsoft.AspNetCore.Http.HttpContext parameter.
        //
        // Parameters:
        //   scopes:
        //     Scopes to request for the downstream API to call.
        //
        //   tenantId:
        //     Enables to override the tenant/account for the same identity. This is useful
        //     in the cases where a given account is guest in other tenants, and you want to
        //     acquire tokens for a specific tenant.
        //
        //   userFlow:
        //     Azure AD B2C UserFlow to target.
        //
        //   user:
        //     Optional claims principal representing the user. If not provided, will use the
        //     signed-in user (in a web app), or the user for which the token was received (in
        //     a web API) cases where a given account is guest in other tenants, and you want
        //     to acquire tokens for a specific tenant, like where the user is a guest in.
```

Could you try removing the `user` param and check if it works?

**Comment by hrazmsft** [comment] 2020-08-12 21:28
Hi @TiagoBrenck, thank you for your reply.

Yes, I've already tried without it and the `GetAccessTokenForUserAsync` crashes with `NullObjectException` internally (something related to the `HttpContext`...)

**Comment by TiagoBrenck** [comment] 2020-08-12 21:38
This looks like a bug on the library then. Do you mind transferring this issue to their repo? https://github.com/AzureAD/microsoft-identity-web/tree/master/src/Microsoft.Identity.Web

**Comment by hrazmsft** [comment] 2020-08-12 23:19
I'm not sure it is a bug. The library needs the request, but it has already been deleted while we waited for the event...

I can ask there what to do in this case...

**Comment by TiagoBrenck** [comment] 2020-08-12 23:37
The code is looking for the token in this HttpContext item: `httpContext.Items["JwtSecurityTokenUsedToCallWebAPI"]`;

Maybe you could try populating this item on your callback?

**Comment by hrazmsft** [comment] 2020-08-13 08:29
No, I can't access to `Items` because the object has been disposed:

![image](https://user-images.githubusercontent.com/66222191/90112089-36888a80-dd58-11ea-8602-97e39e097005.png)

**Comment by jmprieur** [comment] 2020-08-13 08:30
See https://github.com/AzureAD/microsoft-identity-web/issues/441

**Comment by derisen** [comment] 2020-08-14 17:06
The issue is transferred. Closing this now.

**Closed as completed by derisen** 2020-08-14 17:06 UTC
Labels: question
